// Barrel for the v2 design-system components (D-W0.11). "Is this page on
// v2?" is a grep for `@/components/ds`.
export { Icon } from "./Icon";
export type { IconProps } from "./Icon";
export { MetricValue } from "./MetricValue";
export type { MetricValueProps } from "./MetricValue";
export { AnimatedNumber } from "./AnimatedNumber";
export type { AnimatedNumberProps } from "./AnimatedNumber";
export { AnimatedFill } from "./AnimatedFill";
export type { AnimatedFillProps } from "./AnimatedFill";
export { Card } from "./Card";
export type { CardProps, CardVariant } from "./Card";
export { SectionLabel } from "./SectionLabel";
export type { SectionLabelAction } from "./SectionLabel";
export { TintedChip } from "./TintedChip";
export type { TintedChipProps, TintedChipSize } from "./TintedChip";
export { DeltaChip } from "./DeltaChip";
export type { DeltaChipProps } from "./DeltaChip";
export { RecordChip } from "./RecordChip";
export { ImprovementChip } from "./ImprovementChip";
export { Avatar, initialsFor, colorForSeed } from "./Avatar";
export type { AvatarProps } from "./Avatar";
export { CountPill } from "./CountPill";
export type { CountPillProps } from "./CountPill";
export { Button } from "./Button";
export type { ButtonProps, ButtonVariant, ButtonSize } from "./Button";
export { IconButton } from "./IconButton";
export type { IconButtonProps } from "./IconButton";
export { Tooltip } from "./Tooltip";
export type { TooltipProps } from "./Tooltip";
export { SegmentedControl } from "./SegmentedControl";
export type { SegmentedControlOption, SegmentedControlProps } from "./SegmentedControl";
export { Tabs } from "./Tabs";
export type { TabItem, TabsProps } from "./Tabs";
export { Switch } from "./Switch";
export type { SwitchProps } from "./Switch";
export { Checkbox } from "./Checkbox";
export type { CheckboxProps } from "./Checkbox";
export { ChoiceTileGroup } from "./ChoiceTile";
export type { ChoiceTileOption, ChoiceTileGroupProps } from "./ChoiceTile";
