-- Persisted daily step counts: one row per user per day. The app reads steps
-- from the device's health store and upserts the running daily total, so a
-- (user_id, entry_date) uniqueness guard keeps a day from being duplicated.

create table daily_step_counts (
    id         bigint generated by default as identity primary key,
    user_id    bigint  not null references users (id) on delete cascade,
    entry_date date    not null,
    steps      integer not null,
    constraint daily_step_counts_user_id_entry_date_key unique (user_id, entry_date)
);

create index daily_step_counts_user_id_idx on daily_step_counts (user_id);
