-- Initial schema for the Lifey fitness & nutrition tracker.

create table users (
    id         bigint generated by default as identity primary key,
    email      varchar(255) not null unique,
    created_at timestamp with time zone not null
);

create table foods (
    id               bigint generated by default as identity primary key,
    name             varchar(255) not null,
    calories_per_100g double precision not null,
    protein_per_100g  double precision not null,
    carbs_per_100g    double precision,
    fat_per_100g      double precision
);

create table recipes (
    id          bigint generated by default as identity primary key,
    name        varchar(255) not null,
    description varchar(2000)
);

create table recipe_ingredients (
    id                bigint generated by default as identity primary key,
    recipe_id         bigint not null references recipes (id),
    food_id           bigint not null references foods (id),
    quantity_in_grams double precision not null
);

create table meals (
    id        bigint generated by default as identity primary key,
    date_time timestamp not null,
    meal_type varchar(20) not null
);

create table meal_entries (
    id                bigint generated by default as identity primary key,
    meal_id           bigint not null references meals (id),
    food_id           bigint not null references foods (id),
    quantity_in_grams double precision not null
);

create table exercises (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table workout_templates (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table workout_template_exercises (
    id                  bigint generated by default as identity primary key,
    workout_template_id bigint not null references workout_templates (id),
    exercise_id         bigint not null references exercises (id)
);

create table workout_sessions (
    id          bigint generated by default as identity primary key,
    started_at  timestamp with time zone not null,
    finished_at timestamp with time zone
);

create table exercise_sets (
    id                 bigint generated by default as identity primary key,
    workout_session_id bigint not null references workout_sessions (id),
    exercise_id        bigint not null references exercises (id),
    reps               integer not null,
    weight             double precision not null
);

create table weight_entries (
    id         bigint generated by default as identity primary key,
    entry_date date not null,
    weight     double precision not null
);
