-- Biometric/profile data collected at onboarding. One row per user,
-- created when the user completes (or partially completes) onboarding.
-- Weight is NOT here: weight history lives in weight_entries.
create table user_details (
    id                      bigint generated by default as identity primary key,
    user_id                 bigint      not null unique references users (id) on delete cascade,
    gender                  varchar(20) not null,  -- MALE | FEMALE | UNSPECIFIED
    birth_date              date        not null,
    height_cm               double precision not null, -- metric canonical, imperial converted client-side
    activity_level          varchar(20) not null,  -- SEDENTARY | LIGHT | MODERATE | ACTIVE | VERY_ACTIVE
    primary_goal            varchar(20) not null,  -- LOSE_WEIGHT | MAINTAIN | GAIN_MUSCLE
    target_weight_kg        double precision,
    onboarding_completed_at timestamptz not null default now(),
    updated_at              timestamptz not null default now()
);
