-- Profile picture storage: at most one row per user. `source` distinguishes an
-- explicit upload from an auto-imported Google account picture — GOOGLE rows
-- are only ever written when no row exists yet, so an upload always wins and
-- is never silently overwritten by a later social login.
create table user_avatars (
    id           bigint generated by default as identity primary key,
    user_id      bigint      not null unique references users (id) on delete cascade,
    image        bytea       not null,
    content_type varchar(50) not null,
    source       varchar(20) not null,  -- UPLOAD | GOOGLE
    updated_at   timestamptz not null default now()
);
