-- Recipe photos: at most one row per recipe. Two JPEGs are stored per row —
-- a resized main image (long side capped) for the detail view, and a
-- square-cropped thumbnail for list/grid views — so list endpoints never need
-- to crop/resize on the fly. Separate table (not columns on `recipes`), same
-- reasoning as `user_avatars`: the frequent list/delta-sync reads of recipes
-- must never load these bytes.
create table recipe_images (
    id           bigint generated by default as identity primary key,
    recipe_id    bigint      not null unique references recipes (id) on delete cascade,
    image        bytea       not null,
    thumbnail    bytea       not null,
    content_type varchar(50) not null,
    updated_at   timestamptz not null default now()
);

-- Denormalized onto the parent row so RecipeMapper can read it off an
-- already-loaded Recipe without an extra query per row on findAll/findPage/
-- findDelta. Distinct from `recipes.updated_at` (which also bumps on any
-- other field edit) so mobile clients only re-download the image when this
-- specifically changes.
alter table recipes add column image_updated_at timestamptz;
