-- Push device registration (docs/30-push-notifications-plan.md, B1). One row
-- per device token; upsert-by-token on register, soft-deleted on logout or
-- when the provider reports the token as invalid.

create table push_devices (
    id                  bigint generated by default as identity primary key,
    user_id             bigint       not null references users (id) on delete cascade,
    platform            varchar(20)  not null,
    token               varchar(200) not null,
    last_registered_at  timestamp with time zone not null,
    deleted_at          timestamp with time zone,
    constraint push_devices_token_key unique (token)
);

create index push_devices_user_id_idx on push_devices (user_id);
