-- Subscription/entitlement mirror for both billing rails (docs/landing_page/64-billing-backend-plan.md
-- D-B1): one row per (user, provider), so a user with both a trainer Stripe subscription and a
-- store Pro subscription is two rows, not a three-way merge. Nothing but SubscriptionWriter is
-- meant to write this table (D-B2); everything else reads it through EntitlementService (D-B3).
create table subscription (
    id                        bigint generated by default as identity primary key,
    user_id                   bigint not null references users (id) on delete cascade,
    provider                  varchar(16) not null,   -- STRIPE | APP_STORE | PLAY_STORE | COMP
    status                    varchar(16) not null,   -- TRIALING | ACTIVE | PAST_DUE | CANCELED | EXPIRED | REFUNDED
    plan                      varchar(16),             -- STARTER | PRO | STUDIO — trainer subscriptions only
    provider_customer_id      varchar(255),
    provider_subscription_id  varchar(255),
    current_period_end        timestamptz,
    trial_ends_at             timestamptz,
    cancel_at_period_end      boolean not null default false,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    constraint subscription_user_provider_unique unique (user_id, provider)
);

create index subscription_user_id_idx on subscription (user_id);

-- One provider-side subscription can only ever back one local row (docs/landing_page/64 D-B6).
create unique index subscription_provider_subscription_id_unique
    on subscription (provider_subscription_id)
    where provider_subscription_id is not null;

-- The reconciliation job (docs/landing_page/64 §7) scans non-terminal rows ordered by expiry.
create index subscription_status_current_period_end_idx on subscription (status, current_period_end);
