-- Idempotency ledger for webhook/notification delivery across both billing rails
-- (docs/landing_page/64-billing-backend-plan.md §5.4). A duplicate (provider, event_id)
-- insert short-circuits the handler instead of double-applying a subscription change.
create table processed_billing_event (
    id           bigint generated by default as identity primary key,
    provider     varchar(16) not null,
    event_id     varchar(255) not null,
    event_type   varchar(64) not null,
    processed_at timestamptz not null default now(),
    constraint processed_billing_event_provider_event_unique unique (provider, event_id)
);

-- Pruning support; the ledger must not be pruned more aggressively than 90 days (docs/landing_page/64 §11.6).
create index processed_billing_event_processed_at_idx on processed_billing_event (processed_at);
