-- Per-user, per-month AI call counter (docs/landing_page/64-billing-backend-plan.md §3.4,
-- Prompt 12) — incremented on every *successful* AI call so EntitlementResponse
-- .aiCreditsRemaining can reflect real usage instead of the flat monthly allowance.
-- V74/V75 were already taken by processed_billing_event and the trainer-trial backfill
-- (Prompts 1 and 7), so this lands as V76, the next free version at the time of this prompt.
create table ai_usage_counter (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id) on delete cascade,
    year_month  varchar(7) not null,   -- "yyyy-MM", e.g. "2026-08"; varchar (not char) to match
                                        -- Hibernate's mapping for the entity's plain String field
    used_count  integer not null default 0,
    constraint ai_usage_counter_user_year_month_unique unique (user_id, year_month)
);

create index ai_usage_counter_user_id_idx on ai_usage_counter (user_id);
