-- Trainer access requests (docs/landing_page/66-trainer-billing-web-plan.md §2,
-- D-T1): role granting is a super-admin action (63 §6), so the landing page's
-- "start free trial" CTA cannot self-serve — it creates this row instead, and
-- a super admin decides. V76 was already taken by ai_usage_counter
-- (64 Prompt 12), so this lands as V77, the next free version.
--
-- The partial unique index below is what actually enforces "one open request
-- per user" (D-T1) — not just application code.
create table trainer_request (
    id            bigint generated by default as identity primary key,
    user_id       bigint not null references users (id) on delete cascade,
    status        varchar(16) not null,   -- PENDING | APPROVED | REJECTED
    motivation    text,
    client_count  integer,
    signup_source varchar(255),
    created_at    timestamptz not null default now(),
    decided_at    timestamptz,
    decided_by    bigint                  -- the deciding super admin's user id; no FK,
                                           -- same convention as role_audit_log.actor_id
);

create index trainer_request_user_id_idx on trainer_request (user_id);

create unique index trainer_request_one_pending_per_user_unique
    on trainer_request (user_id)
    where status = 'PENDING';
