-- Body measurements (docs/80 §2.2, §3): one row per (date, site) fact, waist/chest/hips/
-- arm/thigh in centimetres. A synced entity shaped like weight_entries — soft delete
-- via deleted_at, delta feed ordered by (updated_at, id).
--
-- site is a varchar + check rather than a Postgres enum so a new site is an additive
-- constraint change, not an ALTER TYPE. Two rows for the same site and date are allowed
-- on purpose (same as weight); the client shows the newest as the day's value.
create table body_measurements (
    id          bigint generated by default as identity primary key,
    user_id     bigint           not null references users (id) on delete cascade,
    entry_date  date             not null,
    site        varchar(16)      not null,
    value_cm    double precision not null,
    created_at  timestamptz      not null default now(),
    updated_at  timestamptz      not null default now(),
    deleted_at  timestamptz,
    constraint body_measurements_site_ck check (site in ('WAIST', 'CHEST', 'HIPS', 'ARM', 'THIGH')),
    constraint body_measurements_value_ck check (value_cm > 0 and value_cm <= 300)
);

create index body_measurements_user_id_idx on body_measurements (user_id);
create index idx_body_measurements_updated_at on body_measurements (updated_at, id);
