-- Progress photos (docs/80 §2.4, §2.5, §3): a dated, optionally pose-tagged photo in the
-- owner's timeline. Metadata and bytes live in two tables on purpose — a list query reads
-- only progress_photos and never drags megabytes of bytea (same split rationale as
-- user_avatars / recipe_images, which the entity javadoc explains).
--
-- Not a synced entity: photos are online-only (docs/80 §2.1), so there is no updated_at /
-- deleted_at tombstone pair for the delta feed, and deleting a photo is a hard delete of
-- both rows (docs/80 §6). The image row also cascades from the photo row, and the photo
-- row from the user, so account deletion leaves no body photos behind.
--
-- pose is a varchar + check rather than a Postgres enum so a new pose is additive.
create table progress_photos (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null references users (id) on delete cascade,
    taken_on   date         not null,
    pose       varchar(16)  not null,
    note       varchar(500),
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),
    constraint progress_photos_pose_ck check (pose in ('FRONT', 'SIDE', 'BACK', 'OTHER'))
);

create index progress_photos_user_taken_idx on progress_photos (user_id, taken_on desc, id desc);

create table progress_photo_images (
    id           bigint generated by default as identity primary key,
    photo_id     bigint      not null references progress_photos (id) on delete cascade,
    image        bytea       not null,
    thumbnail    bytea       not null,
    content_type varchar(50) not null,
    updated_at   timestamptz not null default now(),
    constraint progress_photo_images_photo_unique unique (photo_id)
);
