-- Per-user preferences: unit system, daily calorie/macro goals, theme.
-- One row per user, created lazily by the app on first access rather than here.

create table user_settings (
    id                 bigint generated by default as identity primary key,
    user_id            bigint      not null unique references users (id) on delete cascade,
    unit_system        varchar(20) not null default 'METRIC',
    daily_calorie_goal integer,
    daily_protein_goal integer,
    daily_carbs_goal   integer,
    daily_fat_goal     integer,
    theme              varchar(20) not null default 'SYSTEM'
);
