-- Tracks which exercises are planned for a session (e.g. copied in from a
-- template at creation time), independent of the sets actually logged for
-- them. A snapshot only: no FK back to workout_templates, so editing a
-- session can never affect the template it started from.

create table workout_session_exercises (
    id                  bigint generated by default as identity primary key,
    workout_session_id bigint not null references workout_sessions (id) on delete cascade,
    exercise_id         bigint not null references exercises (id)
);

create index workout_session_exercises_session_id_idx on workout_session_exercises (workout_session_id);
