-- Water intake tracking: reusable volume presets ("sources", e.g. "Creatine
-- Shake" = 0.9L) and logged intake entries. Entries snapshot their volume at
-- creation time, so editing/deleting a source never changes past entries.

create table water_sources (
    id            bigint generated by default as identity primary key,
    user_id       bigint           not null references users (id) on delete cascade,
    name          varchar(255)     not null,
    volume_liters double precision not null
);

create index water_sources_user_id_idx on water_sources (user_id);

create table water_entries (
    id              bigint generated by default as identity primary key,
    user_id         bigint                   not null references users (id) on delete cascade,
    water_source_id bigint references water_sources (id) on delete set null,
    volume_liters   double precision         not null,
    consumed_at     timestamp with time zone not null
);

create index water_entries_user_id_idx on water_entries (user_id);

-- Daily water goal lives alongside the other per-user daily goals.
alter table user_settings add column daily_water_goal_liters double precision;
