import Foundation
import WatchConnectivity

/// Posted when a `standaloneSessionAck` arrives (docs/watch/
/// 44-watch-f6-standalone-plan.md §4.2) — lets the summary screen (S9/S11)
/// flip its `sync_pending` chip to `sync_done` without `PhoneConnector`
/// having to reach into `WorkoutManager`'s standalone-mode state directly.
/// `userInfo["standaloneSessionId"]` is the acked session's id.
extension Notification.Name {
  static let standaloneSessionAcked = Notification.Name("LifeyStandaloneSessionAcked")
}

/// Watch-side `WCSessionDelegate` — mirrors Android's `PhoneListenerService`
/// + `SummarySender` combined (docs/40-watch-app-plan.md §4.3, §4.5, §3).
/// Applies phone-pushed context/messages to `WorkoutManager` and sends the
/// summary/startRejected/endRequested messages back. The phone-side
/// counterpart (`Runner/WatchBridge.swift`) already implements its half of
/// every path used here.
final class PhoneConnector: NSObject {
  static let shared = PhoneConnector()

  private override init() {
    super.init()
  }

  /// Called from `AppDelegate.applicationDidFinishLaunching()` — as early as
  /// possible, so a `transferUserInfo`/applicationContext already queued by
  /// the phone isn't missed (mirrors the phone-side WatchBridge.swift's own
  /// comment on this).
  func activate() {
    guard WCSession.isSupported() else { return }
    WCSession.default.delegate = self
    WCSession.default.activate()
  }

  // MARK: - Watch → phone (docs/40-watch-app-plan.md §3 "Lezárás", §5.3, §8.2)

  /// Queued delivery via `transferUserInfo` — arrives even if the phone app
  /// isn't running right now, unlike `sendMessage` (docs/40-watch-app-plan.md
  /// §3 "Lezárás").
  func sendSummary(
    sessionClientId: String, activeCalories: Double?, averageHeartRate: Double?,
    healthWorkoutId: String?
  ) {
    guard WCSession.isSupported() else { return }
    var userInfo: [String: Any] = ["sessionClientId": sessionClientId]
    if let activeCalories { userInfo["activeCalories"] = activeCalories }
    if let averageHeartRate { userInfo["averageHeartRate"] = averageHeartRate }
    if let healthWorkoutId { userInfo["healthWorkoutId"] = healthWorkoutId }
    WCSession.default.transferUserInfo(userInfo)
  }

  func sendStartRejected(sessionClientId: String) {
    sendMessage(["type": "startRejected", "sessionClientId": sessionClientId])
  }

  /// [rpe] is whatever `EffortSelectorView`'s stepper produced (nil if the
  /// user skipped it) — the key is omitted entirely when nil, never sent as
  /// `NSNull`, which `sendMessage`'s property-list encoding rejects (the
  /// same pitfall already hit `restEndsAtEpochMs`, docs/40-watch-app-plan.md
  /// §11.2).
  func sendEndRequested(sessionClientId: String, rpe: Int?) {
    var message: [String: Any] = ["type": "endRequested", "sessionClientId": sessionClientId]
    if let rpe { message["rpe"] = rpe }
    sendMessage(message)
  }

  /// The watch's "+1 set" tap (docs/watch/43-watch-f5-set-logging-plan.md
  /// §4.1) — no exercise/reps/weight on the wire, the phone logs the next
  /// row from its own current position (§2, §5.2). [eventId] is generated by
  /// `WorkoutManager.logSet()`, used for dedup (§4.2) and to correlate the
  /// eventual `logSetAck` back to this specific tap.
  /// [reps]/[weight] are what the adjust stepper produced (docs/watch/
  /// 48-watch-f5b-set-adjust-plan.md §4.1) — both nil for a plain F5a
  /// one-tap log. The keys are **omitted entirely** when nil, never sent as
  /// `NSNull`, which `sendMessage`'s property-list encoding rejects (the
  /// same pitfall that already hit `restEndsAtEpochMs` and `rpe` —
  /// docs/40-watch-app-plan.md §11.2).
  func sendLogSet(
    sessionClientId: String, eventId: String, loggedAtEpochMs: Int64, reps: Int? = nil,
    weight: Double? = nil
  ) {
    var message: [String: Any] = [
      "type": "logSet", "sessionClientId": sessionClientId, "eventId": eventId,
      "loggedAtEpochMs": loggedAtEpochMs,
    ]
    if let reps { message["reps"] = reps }
    if let weight { message["weight"] = weight }
    sendMessage(message)
  }

  /// The watch's own `HKWorkoutSession` actually started running — drives the
  /// phone's "Measuring" pill (docs/40-watch-app-plan.md §12.4 B14). Sent
  /// once per watch session by `WorkoutManager`, not on every state sync.
  func sendStartedOnWatch(sessionClientId: String) {
    sendMessage(["type": "startedOnWatch", "sessionClientId": sessionClientId])
  }

  /// Live heart-rate/calorie readings, pushed every time
  /// `HKLiveWorkoutBuilderDelegate` reports fresh data — far more often than
  /// `sendSummary`'s one-shot totals. Best-effort like the other `sendMessage`
  /// calls here: a reading dropped while unreachable is superseded moments
  /// later by the next one, so there's no `transferUserInfo`-style delivery
  /// guarantee to bother with.
  func sendLiveMetrics(sessionClientId: String, heartRateBpm: Double?, activeCalories: Double?) {
    var message: [String: Any] = ["type": "liveMetrics", "sessionClientId": sessionClientId]
    if let heartRateBpm { message["heartRateBpm"] = heartRateBpm }
    if let activeCalories { message["activeCalories"] = activeCalories }
    sendMessage(message)
  }

  private func sendMessage(_ message: [String: Any]) {
    // Best-effort, like the phone side's own sendMessage calls — a lost
    // startRejected/endRequested simply means the user retries
    // (docs/40-watch-app-plan.md §8.1).
    guard WCSession.isSupported(), WCSession.default.isReachable else { return }
    WCSession.default.sendMessage(message, replyHandler: nil, errorHandler: nil)
  }

  // MARK: - Standalone sessions (docs/watch/44-watch-f6-standalone-plan.md §4.1, §4.2)

  /// Queues a just-closed standalone session for delivery — mirrors
  /// `sendSummary`'s `transferUserInfo` (queued: arrives even if the phone
  /// app isn't running, delivered whenever it next connects). The `type`
  /// key is what lets `Runner/WatchBridge.swift` tell this apart from an
  /// ordinary summary. Doesn't remove [payload] from `StandaloneSessionStore`
  /// itself — only the eventual `standaloneSessionAck` does that (§4.2), so
  /// a delivery that never lands simply gets retried by
  /// `flushPendingStandaloneSessions()`.
  func sendStandaloneSession(_ payload: StandaloneSessionPayload) {
    guard WCSession.isSupported(), var dictionary = propertyListDictionary(from: payload) else {
      return
    }
    dictionary["type"] = "standaloneSessionCompleted"
    WCSession.default.transferUserInfo(dictionary)
  }

  /// Re-sends every not-yet-acked standalone session from the local queue —
  /// called on activation, reachability regained, and right after a session
  /// closes (`WorkoutManager.endStandalone`, S9). `transferUserInfo` itself
  /// already tolerates being called while unreachable (it queues), so this
  /// is only about re-triggering delivery at moments it's newly likely to
  /// land, not a correctness requirement on its own.
  func flushPendingStandaloneSessions() {
    for payload in StandaloneSessionStore.shared.all() {
      sendStandaloneSession(payload)
    }
  }

  // MARK: - Live bridging (watch-started session adopted by the phone)

  /// Queues a running-session snapshot for delivery — same `transferUserInfo`
  /// queued-delivery guarantee as `sendStandaloneSession`, tagged with a
  /// different `type` so `Runner/WatchBridge.swift` can tell "still running"
  /// apart from "finished". `WorkoutManager.sendAdoptionRequestIfNeeded()` is
  /// the only caller — it already gates on reachability/not-yet-adopted, so
  /// this itself has no retry/queue of its own the way
  /// `flushPendingStandaloneSessions()` does (an adoption snapshot going
  /// stale before delivery isn't a correctness problem the way a lost
  /// finished-session payload would be — the next reachability-regain or
  /// logged set simply sends a fresher one).
  func sendStandaloneAdoption(_ payload: StandaloneAdoptionPayload) {
    guard WCSession.isSupported(), var dictionary = propertyListDictionary(from: payload) else {
      return
    }
    dictionary["type"] = "standaloneSessionAdopted"
    WCSession.default.transferUserInfo(dictionary)
  }

  /// `transferUserInfo` needs a plain property-list `[String: Any]`, not a
  /// `Codable` value directly — bridges via `JSONEncoder`/`JSONSerialization`
  /// rather than building the dictionary by hand. Synthesized `Encodable`
  /// omits a nil-valued `Optional` field's key entirely (rather than writing
  /// JSON `null`), which matters here: a property list has no null value,
  /// and `transferUserInfo` would silently drop the whole payload if one
  /// slipped through (the same pitfall `Runner/WatchBridge.swift`'s
  /// `sanitizedForPropertyList` exists for on the phone side). Generic over
  /// both standalone payload shapes (finished/still-running) rather than
  /// duplicated per type.
  private func propertyListDictionary<T: Encodable>(from payload: T) -> [String: Any]? {
    guard let data = try? JSONEncoder().encode(payload) else { return nil }
    return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
  }
}

// MARK: - WCSessionDelegate

extension PhoneConnector: WCSessionDelegate {
  func session(
    _ session: WCSession, activationDidCompleteWith activationState: WCSessionActivationState,
    error: Error?
  ) {
    // Picks up a context pushed before this delegate was set (e.g. the
    // phone's `startWorkout` call raced `handle(_:)`'s app launch).
    applyContext(session.receivedApplicationContext)
    Task { @MainActor in
      WorkoutManager.shared.applyReachabilityChanged(session.isReachable)
      if session.isReachable { WorkoutManager.shared.sendAdoptionRequestIfNeeded() }
    }
    flushPendingStandaloneSessions()
  }

  /// Feeds the log-set control's "phone unreachable" ghosted state
  /// (docs/watch/43-watch-f5-set-logging-plan.md §4.4's iOS branch) — the
  /// exact same `WCSession.isReachable`/`sessionReachabilityDidChange` pair
  /// `Runner/WatchBridge.swift` already uses for the opposite direction.
  /// Also the standalone queue's retry trigger: reachability regained is
  /// exactly when a previously-queued `transferUserInfo` is newly likely to
  /// land (docs/watch/44-watch-f6-standalone-plan.md §4.1) — and, for live
  /// bridging, exactly when a not-yet-adopted standalone session should
  /// (re-)send its adoption snapshot (`sendAdoptionRequestIfNeeded()` is a
  /// no-op once already adopted or if this isn't a standalone session).
  func sessionReachabilityDidChange(_ session: WCSession) {
    Task { @MainActor in
      WorkoutManager.shared.applyReachabilityChanged(session.isReachable)
      if session.isReachable { WorkoutManager.shared.sendAdoptionRequestIfNeeded() }
    }
    if session.isReachable {
      flushPendingStandaloneSessions()
    }
  }

  func session(_ session: WCSession, didReceiveApplicationContext applicationContext: [String: Any])
  {
    applyContext(applicationContext)
  }

  func session(_ session: WCSession, didReceiveMessage message: [String: Any]) {
    // Handled before the sessionClientId guard below — a standalone ack
    // (docs/watch/44-watch-f6-standalone-plan.md §4.2) keys off
    // standaloneSessionId instead, since it isn't tied to any single
    // phone-mastered session.
    if message["command"] as? String == "standaloneSessionAck" {
      guard let standaloneSessionId = message["standaloneSessionId"] as? String else { return }
      StandaloneSessionStore.shared.remove(id: standaloneSessionId)
      NotificationCenter.default.post(
        name: .standaloneSessionAcked, object: nil,
        userInfo: ["standaloneSessionId": standaloneSessionId])
      return
    }
    // Same standaloneSessionId-keyed shape as standaloneSessionAck above —
    // an adoption ack isn't tied to any single phone-mastered session either.
    if message["command"] as? String == "adoptionAck" {
      guard let standaloneSessionId = message["standaloneSessionId"] as? String else { return }
      Task { @MainActor in
        WorkoutManager.shared.applyAdoptionAck(standaloneSessionId: standaloneSessionId)
      }
      return
    }
    guard let sessionClientId = message["sessionClientId"] as? String else { return }
    switch message["command"] as? String {
    case "state":
      applyState(
        sessionClientId: sessionClientId, title: nil, state: message["state"] as? [String: Any])
    case "end":
      // A stray `end` for a phone-mastered session must not be able to
      // close a running standalone session that was never adopted — but
      // once adopted, the phone genuinely does know about it and ending
      // from either side should work (live bridging). Routes to
      // `endStandalone` rather than `finishAndSendSummary()` for any
      // standalone session, adopted or not (D-F6.2's original guard,
      // widened by one case).
      Task { @MainActor in
        let manager = WorkoutManager.shared
        if manager.isStandalone {
          guard manager.isAdopted else { return }
          await manager.endStandalone(rpe: nil)
        } else {
          await manager.finishAndSendSummary()
        }
      }
    case "logSetAck":
      guard let eventId = message["eventId"] as? String, let accepted = message["accepted"] as? Bool
      else { return }
      Task { @MainActor in WorkoutManager.shared.applyLogSetAck(eventId: eventId, accepted: accepted) }
    default:
      break
    }
  }

  /// `desiredPhase: "ended"` is the delivery-guarantee fallback
  /// (docs/40-watch-app-plan.md §3 "Kézbesítési garancia") — mirrors
  /// Android's `onDataChanged` check: the phone's `end` message may never
  /// have reached us while unreachable.
  ///
  /// `applyTemplateSync` runs first and **unconditionally** — a context that
  /// only ever carries `templates` (no session has been started from this
  /// phone yet, the common case right after pairing) has no
  /// `sessionClientId` at all, and the guard below would otherwise discard
  /// the whole context, including the templates, before this function got a
  /// chance to look at it (docs/watch/49-watch-f6b-template-sync-plan.md
  /// T4.1 — the same guard-ordering class of bug the S8 ack handling fixed).
  private func applyContext(_ context: [String: Any]) {
    applyTemplateSync(context)

    guard !context.isEmpty, let sessionClientId = context["sessionClientId"] as? String else {
      return
    }
    applyState(
      sessionClientId: sessionClientId, title: context["title"] as? String,
      state: context["state"] as? [String: Any])
    if context["desiredPhase"] as? String == "ended" {
      Task { @MainActor in
        // Same standalone/adopted guard as the "end" message case above
        // (docs/watch/44-watch-f6-standalone-plan.md D-F6.2, widened for
        // live bridging) — this delivery-guarantee fallback is keyed only
        // on phase, not sessionClientId, so without it a stray phone-
        // mastered desiredPhase:"ended" could otherwise close a running,
        // not-yet-adopted standalone session.
        let manager = WorkoutManager.shared
        if manager.isStandalone {
          guard manager.isAdopted, manager.phase == .active else { return }
          await manager.endStandalone(rpe: nil)
        } else if manager.phase == .active || manager.phase == .ending {
          await manager.finishAndSendSummary()
        }
      }
    }
  }

  /// Decodes `context["templates"]` (docs/watch/49-watch-f6b-template-sync-plan.md
  /// §4.1, T3.2's `syncTemplates` handler) and overwrites the picker's cache.
  /// A no-op — not an error — whenever the key is absent, which is every
  /// context pushed before the phone's first template sync.
  ///
  /// The array already passed through `WatchBridge`'s
  /// `sanitizedForPropertyList` before landing in `applicationContext`, so
  /// it's guaranteed property-list-safe — round-tripping it through
  /// `JSONSerialization` back into `Data` is the simplest way to hand it to
  /// `JSONDecoder`, rather than hand-walking each field the way `applyState`
  /// does for `state` (that one has no Codable type to decode into; this one
  /// does).
  private func applyTemplateSync(_ context: [String: Any]) {
    guard let rawTemplates = context["templates"] as? [[String: Any]] else { return }
    guard let data = try? JSONSerialization.data(withJSONObject: rawTemplates),
      let templates = try? JSONDecoder().decode([CachedTemplate].self, from: data)
    else { return }
    StandaloneSessionStore.shared.saveTemplates(templates)
  }

  private func applyState(sessionClientId: String, title: String?, state: [String: Any]?) {
    Task { @MainActor in
      WorkoutManager.shared.applyStateUpdate(
        sessionClientId: sessionClientId,
        title: title,
        exerciseName: state?["exerciseName"] as? String,
        setsDone: (state?["setsDone"] as? NSNumber)?.intValue,
        setsTotal: (state?["setsTotal"] as? NSNumber)?.intValue,
        restRemainingSeconds: (state?["restRemainingSeconds"] as? NSNumber)?.intValue,
        restTotalSeconds: (state?["restTotalSeconds"] as? NSNumber)?.intValue,
        // The F5b adjust prefill (docs/watch/48-watch-f5b-set-adjust-plan.md
        // §4.2). The phone strips nulls before sending, so "key absent"
        // is how "no prefill" arrives — `as? NSNumber` yields nil either way.
        nextSetReps: (state?["nextSetReps"] as? NSNumber)?.intValue,
        nextSetWeight: (state?["nextSetWeight"] as? NSNumber)?.doubleValue,
        // Which exercise `setsDone`/`setsTotal` are about, for a watch-started
        // session the phone has adopted — see `WorkoutManager.phoneSetsDone`.
        setsDoneExerciseIndex: (state?["setsDoneExerciseIndex"] as? NSNumber)?.intValue,
        // Plain array of ints over the wire; `compactMap` so a malformed entry
        // costs that entry rather than the whole payload.
        setsDonePerExercise: (state?["setsDonePerExercise"] as? [Any])?
          .compactMap { ($0 as? NSNumber)?.intValue })
    }
  }
}
